spring:
  application:
    name: ttl-service
  profiles:
    active: redis #caffeine
  kafka:
    bootstrap-address: PLAINTEXT://localhost:9092
    group-id: ttl_consumer_group
    topic: ttl_events
  cache:
    default-name: default
    ttl-seconds: 5
    max-size: 100